# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

servies:
    - mysql

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install flask
    - pip install coverage
    - pip install sqlalchemy
    - apt-get install libmysqlclient-dev python-dev
    - pip install mysql-python

before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -e 'create database test'

script:
    - date
    - ls -al
    - make check
    - make test
