# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

servies:
    - mysql

sudo: true

before_install:
    - apt-get install python-dev libmysqlclient-dev

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install gunicorn
    - pip install flask-cors
    - pip install Flask-Testing
    - pip install MySQL-python

before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -e 'create database test'
script:
    - date
    - ls -al
    - make check
    - make test
