FORMAT: 1A

# SWEetSpots

SWEetSpots is an API for receiving information on US cities, popular attractions in those cities, and popular restaurants.

## Cities Collection [/scrape/cities]
All cities data in our API
### List All Cities [GET]

+ Response 200 (application/json)

        {
            "cities": [
               {
                    "id": City_ID_as_int,
                    "name": City_Name_as_String,
                    "population": Population_as_int,
                    "country": Country_as_String,
                    "demonym": Demonym_as_String,
                    "elevation": Elevation_as_float,
                    "description": Description_as_string
                }
               
            ]
        }

## City Data [/scrape/cities/{name}]
Specific city data in our API
### Specific City Data [GET]

+ Response 200 (application/json)

        {
            "id": City_ID_as_int,
            "name": City_Name_as_String,
            "population": Population_as_int,
            "country": Country_as_String,
            "demonym": Demonym_as_String,
            "elevation": Elevation_as_float,
            "description": Description_as_string
        }

## Attractions Collection [/scrape/attractions]
All attractions data in our API
### List All Attractions [GET]

+ Response 200 (application/json)

        {
            "attractions": [
                {
                    "id": Attraction_ID_as_int,
                    "name": Name_as_String,
                    "rating": Rating_as_float,
                    "location": Location_as_String,
                    "num_reviews": Reviews_as_int,
                    "category": Category_as_String,
                }
            ]
        }
        
## Attraction Data [/scrape/attractions/{name}]
Specific attraction data in our API
### Specific Attraction Data [GET]

+ Response 200 (application/json)

        {
            "id": Attraction_ID_as_int,
            "name": Name_as_String,
            "rating": Rating_as_float,
            "city_id": City__ID_as_int,
            "num_reviews": Reviews_as_float,
            "category": Category_as_String,
        }
        
## Restaurants Collection [/scrape/restaurants]
All restaurants data in our API
### List All Restaurants [GET]

+ Response 200 (application/json)

        {
            "restaurants":[
                {
                    "id": Restaurant_ID_as_int,
                    "name": Name_as_String,
                    "rating": Rating_as_float,
                    "city_id": City_ID_as_int,
                    "category": Category_as_String,
                    "address": Address_as_string
                }
            ]
        }
        
## Resaurant Data [/scrape/restaurants/{name}]
All restaurants data in our API
### Specific Restaurant Data [GET]

+ Response 200 (application/json)

        {
            "id": Restaurant_ID_as_int,
            "name": Name_as_String,
            "rating": Rating_as_float,
            "city_id": City_ID_as_int,
            "category": Category_as_String,
            "address": Address_as_string
        }