FORMAT: 1A

# SWEetSpots

SWEetSpots is an API for receiving information on US cities, popular attractions in those cities, and popular restaurants.

## Cities Collection [/scrape/cities]
All cities data in our API
### List All Cities [GET]

+ Response 200 (application/json)

        {
            "cities": [
               {
                    "city_id": City_ID_as_int,
                    "name": City_Name_as_String,
                    "latitude": Latitude_as_double,
                    "longitude": Longitude_as_double,
                    "population": Population_as_int,
                    "description": Description_as_string
                }
               
            ]
        }

## City Data [/scrape/cities/{name}]
Specific city data in our API
### Specific City Data [GET]

+ Response 200 (application/json)

        {
            "city_id": City_ID_as_int,
            "name": City_Name_as_String,
            "latitude": Latitude_as_double,
            "longitude": Longitude_as_double,
            "population": Population_as_int,
            "description": Description_as_string
        }

## Attractions Collection [/scrape/attractions]
All attractions data in our API
### List All Attractions [GET]

+ Response 200 (application/json)

        {
            "attractions": [
                {
                    "attraction_id": Attraction_ID_as_int,
                    "name": Name_as_String,
                    "rating": Rating_as_double,
                    "location": Location_as_String,
                    "latitude": Latitude_as_double,
                    "longitude": Longitude_as_double,
                    "description": Description_as_String,
                }
            ]
        }
        
## Attraction Data [/scrape/attractions/{name}]
Specific attraction data in our API
### Specific Attraction Data [GET]

+ Response 200 (application/json)

        {
            "attraction_id": Attraction_ID_as_int,
            "name": Name_as_String,
            "rating": Rating_as_double,
            "location": Location_as_String,
            "latitude": Latitude_as_double,
            "longitude": Longitude_as_double,
            "description": Description_as_String,
        }
        
## Resaurants Collection [/scrape/restaurants]
All restaurants data in our API
### List All Restaurants [GET]

+ Response 200 (application/json)

        {
            "restaurants":[
                {
                    "restaurant_id": Restaurant_ID_as_int,
                    "name": Name_as_String,
                    "rating": Rating_as_double,
                    "location": Location_as_String,
                    "Category": Category_as_String,
                    "Address": Address_as_string
                }
            ]
        }
        
## Resaurant Data [/scrape/restaurants/{name}]
All restaurants data in our API
### Specific Restaurant Data [GET]

+ Response 200 (application/json)

        {
            "restaurant_id": Restaurant_ID_as_int,
            "name": Name_as_String,
            "rating": Rating_as_double,
            "location": Location_as_String,
            "Category": Category_as_String,
            "Address": Address_as_string
        }